# Generated by Django 4.0.6 on 2022-07-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_adress',
            new_name='email',
        ),
    ]
